CREATE TABLE Student (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usn VARCHAR UNIQUE,
    name VARCHAR(20)
);


CREATE TABLE Subject (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20),
    std_id BIGINT,
    FOREIGN KEY (std_id) REFERENCES Student(id)
);


CREATE TABLE RESULT (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s_id BIGINT,
    sem BIGINT CHECK (sem BETWEEN 1 AND 8) NOT NULL ,
    sub_id BIGINT,
    marks INT,
    FOREIGN KEY (s_id) REFERENCES Student(id),
    FOREIGN KEY (sub_id) REFERENCES Subject(id)
);

INSERT INTO Student (usn,  name) VALUES
('USN001', 'ullas'),
('USN002', 'preetham'),
('USN003', 'varsha'),
('USN004', 'jeevan'),
('USN005', 'yashwanth');

INSERT INTO Subject (name, std_id) VALUES
('Math', 1),
('Physics', 1),
('Chemistry', 2),
('Biology', 2),
('Computer Science', 3);


INSERT INTO RESULT (s_id, sem ,sub_id,marks) VALUES
(1, 3, 1, 85),
(2, 4, 2, 56),
(3, 2, 3, 67),
(4, 1, 4, 67),
(5, 5, 5, 77);

--indexes
--uuid

-- given a particular sem return all students student name and sem

SELECT DISTINCT s.name, e.sem FROM student s LEFT JOIN RESULT e on s.id = e.s_id  WHERE sem =5 ;

-- given a particular usn and sem  return sub name and marks
SELECT s.name, e.marks ,e.sem FROM student s
LEFT JOIN RESULT e  on s.id = e.s_id
LEFT JOIN subject sub on  e.sub_id=sub.id 
WHERE e.sem = 2 and sub.id = 3 ;

--given usn get latest sem marks
SELECT * FROM RESULT e
LEFT JOIN subject ON e.sub_id = subject.id
LEFT JOIN student s ON e.s_id =  s.id
WHERE s.usn = 'USN001'
ORDER BY e.sem DESC LIMIT 1;

--given usn get latest sem marks
SELECT * FROM RESULT e
LEFT JOIN subject ON e.sub_id = subject.id
LEFT JOIN student s ON e.s_id =  s.id
WHERE s.usn = 'USN001'
ORDER BY e.sem;

--given usn and sem get that sem's percentage
SELECT *  FROM RESULT e
LEFT JOIN subject ON e.sub_id = subject.id
LEFT JOIN student s ON e.s_id =  s.id
WHERE s.usn = 'USN005'
;
--given usn and sem get that sem's percentage
SELECT s.name, AVG(marks) FROM RESULT e
LEFT JOIN subject ON e.sub_id = subject.id
LEFT JOIN student s ON e.s_id =  s.id
WHERE s.usn = 'USN005' and e.sem=5
GROUP BY s.name;

--given usn and sem get current sem's percentage
SELECT  s.name, s.usn , e.sem ,AVG(marks) FROM RESULT e
LEFT JOIN subject ON e.sub_id = subject.id
LEFT JOIN student s ON e.s_id =  s.id
WHERE s.usn = 'USN005'
GROUP BY e.sem ,s.name ,s.usn ;

SELECT DISTINCT  student.name ,RESULT1.avg ,RESULT.sem FROM student 
inner JOIN RESULT on student.id =RESULT.s_id and student.usn ='USN005'
LEFT JOIN (
SELECT  e.sem ,AVG(marks) as avg FROM RESULT e
LEFT JOIN subject ON e.sub_id = subject.id
LEFT JOIN student s ON e.s_id =  s.id
WHERE s.usn = 'USN005'
GROUP BY e.sem ) AS RESULT1
ON RESULT.sem =RESULT1.sem ;

--given usn get all sem's percentage
SELECT  s.name, AVG(marks) as CGPA FROM RESULT e
LEFT JOIN subject ON e.sub_id = subject.id
LEFT JOIN student s ON e.s_id =  s.id
WHERE s.usn = 'USN005'
GROUP BY s.name


